export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_AUTH_USER_INFO = 'UPDATE_AUTH_USER_INFO';
export const UPDATE_AUTH_USER_COVER_PICTURE = 'UPDATE_AUTH_USER_COVER_PICTURE';
export const UPDATE_AUTH_USER_PROFILE_PICTURE =
  'UPDATE_AUTH_USER_PROFILE_PICTURE';
